### ISSUE TITLE
'GRACEAdaptor' object has no attribute 'weight'

### ISSUE THREAD

**Issue by BruthYU** [Thartvigsen/GRACE#1]
Thanks a lot for this open source repo :1st_place_medal: 
With the experimental settings of ZSRE based on T5-Small 
```
def F1(model, batch):
    try:
        preds = model.generate(batch["input_ids"], max_length=20).squeeze()
       ...
        return f1
    except Exception as e:
        print(e)
        return 0
```
The metric F1 function will throw out an exception 
```
'GRACEAdaptor' object has no attribute 'weight'
```
This exception occurs in `site-packages/transformers/models/t5/modeling_t5`
```
class T5DenseGatedActDense(nn.Module):
    def __init__(self, config: T5Config):
         ...
    def forward(self, hidden_states):
        ...
        if (
            isinstance(self.wo.weight, torch.Tensor)
            and hidden_states.dtype != self.wo.weight.dtype
            and self.wo.weight.dtype != torch.int8
        ):
            hidden_states = hidden_states.to(self.wo.weight.dtype)
        ...
```

This error can be fixed by adding `self.weight = self.layer.weight` to the `__init__`  function of the GraceAdaptor
But I would like to recommend you to follow the form of [LoraLayer](https://github.com/microsoft/LoRA/blob/main/loralib/layers.py) which inherits the specific type of a module layer

**Comment by Thartvigsen** [comment]
Thanks for identifying this issue and for your suggestion! Exactly what layer are you trying to edit that's leading to this error?

**Comment by BruthYU** [comment]
The layer to be edited is set by the `inner_params` in `/grace/config/model/t5small.yaml`
```
inner_params:
- encoder.block[4].layer[1].DenseReluDense.wo.weight
```

**Comment by Thartvigsen** [comment]
Thanks for the extra info, this will help me debug

**Comment by Thartvigsen** [comment]
Final question @BruthYU, can you confirm you haven't modified anything except for printing the exception? I will try and reproduce the error. If you can add the command you used to produce the error, that would be helpful, too. Thanks!

**Comment by BruthYU** [comment]
To locate the error, I remove the try-except lines like this
```python
def F1(model, batch):
    preds = model.generate(batch["input_ids"], max_length=20).squeeze()
    if len(preds) > 1:
        preds = preds[preds != model.tokenizer.pad_token_id]
    gold_toks = batch["labels"][batch["labels"] != -100].cpu().squeeze() # -100 might be nonsense
    num_same = len(np.intersect1d(preds.cpu().squeeze(), gold_toks))
    if (num_same == 0) or (len(preds.squeeze()) == 0):
        return 0
    precision = num_same / len(preds.squeeze())
    recall = 1.0 * num_same / len(gold_toks)
    f1 = (2 * precision * recall) / (precision + recall)
    return f1
```
The PyCharm will throw out following traceback info:
```shell
Traceback (most recent call last):
  File "/home/yu/github/practice/GRACE/grace/main.py", line 134, in run
    original_edits = torch.tensor([metric(editor, tokenize(e, editor.tokenizer, config["device"])) for e in iter(edit_loader)]).nanmean() # Log first PPL before edits
  File "/home/yu/github/practice/GRACE/grace/main.py", line 134, in <listcomp>
    original_edits = torch.tensor([metric(editor, tokenize(e, editor.tokenizer, config["device"])) for e in iter(edit_loader)]).nanmean() # Log first PPL before edits
  File "/home/yu/github/practice/GRACE/grace/metrics.py", line 63, in F1
    preds = model.generate(batch["input_ids"], max_length=20).squeeze()
  File "/home/yu/anaconda3/envs/peft/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/yu/anaconda3/envs/peft/lib/python3.7/site-packages/transformers/generation/utils.py", line 1323, in generate
    inputs_tensor, model_kwargs, model_input_name
  File "/home/yu/anaconda3/envs/peft/lib/python3.7/site-packages/transformers/generation/utils.py", line 638, in _prepare_encoder_decoder_kwargs_for_generation
    model_kwargs["encoder_outputs"]: ModelOutput = encoder(**encoder_kwargs)
  File "/home/yu/anaconda3/envs/peft/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yu/anaconda3/envs/peft/lib/python3.7/site-packages/transformers/models/t5/modeling_t5.py", line 1097, in forward
    output_attentions=output_attentions,
  File "/home/yu/anaconda3/envs/peft/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yu/anaconda3/envs/peft/lib/python3.7/site-packages/transformers/models/t5/modeling_t5.py", line 753, in forward
    hidden_states = self.layer[-1](hidden_states)
  File "/home/yu/anaconda3/envs/peft/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yu/anaconda3/envs/peft/lib/python3.7/site-packages/transformers/models/t5/modeling_t5.py", line 343, in forward
    forwarded_states = self.DenseReluDense(forwarded_states)
  File "/home/yu/anaconda3/envs/peft/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yu/anaconda3/envs/peft/lib/python3.7/site-packages/transformers/models/t5/modeling_t5.py", line 320, in forward
    isinstance(self.wo.weight, torch.Tensor)
  File "/home/yu/anaconda3/envs/peft/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1270, in __getattr__
    type(self).__name__, name))
AttributeError: 'GRACEAdaptor' object has no attribute 'weight'
```
Other modifications include the default dataset paths, but I don't think they are relevant to this error
```python
class zsRE(Dataset):
    def __init__(self, path="./data/zsre/zsre_dev.jsonl", split="edit"):
        questions, answers = self.load_zsre(path)
```
I run the code with the following instructions
```shell
cd GRACE/grace/
python main.py experiment=qa model=t5small editor=grace
```

**Comment by Thartvigsen** [comment]
I so far haven't been able to reproduce the error, though I did just fix a couple issues with the the main.py file. You might try pulling and running again.

I re-installed this repo from scratch and ran on a new system and just running `python main.py experiment=qa model=t5small editor=grace` is working for me.

I will be away for a few weeks and will check back in on this then and see if I can further assist

**Comment by BruthYU** [comment]
Thx

**Comment by Thartvigsen** [comment]
Hi @BruthYU, could you confirm which version of transformers and pytorch you are using? I noticed your version of Python is different than that of the `environment.yml` file.

**Comment by Thartvigsen** [comment]
I just changed to require torch 2.0.0, too
